name: "Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: cargo install wasm-bindgen-cli
      - run: cargo build --release --target wasm32-unknown-unknown
      - run: wasm-bindgen --out-dir www/src/assets/take-cover --target web ./target/wasm32-unknown-unknown/release/take-cover.wasm
      - run: cp -r assets www/static
      - run: cd www && pnpm install --no-frozen-lockfile && pnpm build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www/build
