name: "Release"

# TODO: Deploy on tags
on:
  push:
    branches:
      - main

env:
  ITCH_TARGET: "kettei-sproutty/take-cover"
  VERSION: ${{ github.ref }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Leafwing-Studios/cargo-cache@v2
      - run: cargo install wasm-bindgen-cli
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
  checks:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - run: cargo clippy --workspace --all-targets --all-features -- --deny warnings
      - run: cargo fmt --all -- --check
  release:
    needs:
      - checks
    runs-on: ubuntu-latest
    steps:
      - name: Install butler
        run: |
          curl -L -o butler.zip 'https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default'
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Build
        run: RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --release --target wasm32-unknown-unknown --no-default-features
      - name: Wasm Bindgen
        run: wasm-bindgen --out-dir www/src/assets/take-cover --target web ./target/wasm32-unknown-unknown/release/take-cover.wasm
      - name: Copy Assets
        run: cp -r assets www/static
      - name: Build Web
        run: cd www && pnpm install --no-frozen-lockfile && pnpm build && cc ..
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: zip -qq -r build.zip www/build
      - name: Upload all packages to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_KEY }}
        run: ./butler push build.zip '${{ env.ITCH_TARGET }}'
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www/build


